/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// Widget struct for Widget
type Widget struct {
	Id     string      `json:"id"`
	Title  string      `json:"title"`
	Width  int32       `json:"width,omitempty"`
	Height int32       `json:"height,omitempty"`
	X      int32       `json:"x,omitempty"`
	Y      int32       `json:"y,omitempty"`
	Type   string      `json:"type"`
	Config interface{} `json:"config"`
}
