/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// TraceGroupsItem struct for TraceGroupsItem
type TraceGroupsItem struct {
	Name      string                 `json:"name"`
	Timestamp *int64                 `json:"timestamp,omitempty"`
	Cursor    IngestionOffsetCursor  `json:"cursor"`
	Metrics   map[string][][]float32 `json:"metrics"`
}

// NewTraceGroupsItem instantiates a new TraceGroupsItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTraceGroupsItem(name string, cursor IngestionOffsetCursor, metrics map[string][][]float32) *TraceGroupsItem {
	this := TraceGroupsItem{}
	this.Name = name
	this.Cursor = cursor
	this.Metrics = metrics
	return &this
}

// NewTraceGroupsItemWithDefaults instantiates a new TraceGroupsItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTraceGroupsItemWithDefaults() *TraceGroupsItem {
	this := TraceGroupsItem{}
	return &this
}

// GetName returns the Name field value
func (o *TraceGroupsItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TraceGroupsItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TraceGroupsItem) SetName(v string) {
	o.Name = v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *TraceGroupsItem) GetTimestamp() int64 {
	if o == nil || o.Timestamp == nil {
		var ret int64
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TraceGroupsItem) GetTimestampOk() (*int64, bool) {
	if o == nil || o.Timestamp == nil {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *TraceGroupsItem) HasTimestamp() bool {
	if o != nil && o.Timestamp != nil {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int64 and assigns it to the Timestamp field.
func (o *TraceGroupsItem) SetTimestamp(v int64) {
	o.Timestamp = &v
}

// GetCursor returns the Cursor field value
func (o *TraceGroupsItem) GetCursor() IngestionOffsetCursor {
	if o == nil {
		var ret IngestionOffsetCursor
		return ret
	}

	return o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value
// and a boolean to check if the value has been set.
func (o *TraceGroupsItem) GetCursorOk() (*IngestionOffsetCursor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cursor, true
}

// SetCursor sets field value
func (o *TraceGroupsItem) SetCursor(v IngestionOffsetCursor) {
	o.Cursor = v
}

// GetMetrics returns the Metrics field value
func (o *TraceGroupsItem) GetMetrics() map[string][][]float32 {
	if o == nil {
		var ret map[string][][]float32
		return ret
	}

	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value
// and a boolean to check if the value has been set.
func (o *TraceGroupsItem) GetMetricsOk() (*map[string][][]float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metrics, true
}

// SetMetrics sets field value
func (o *TraceGroupsItem) SetMetrics(v map[string][][]float32) {
	o.Metrics = v
}

func (o TraceGroupsItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Timestamp != nil {
		toSerialize["timestamp"] = o.Timestamp
	}
	if true {
		toSerialize["cursor"] = o.Cursor
	}
	if true {
		toSerialize["metrics"] = o.Metrics
	}
	return json.Marshal(toSerialize)
}

type NullableTraceGroupsItem struct {
	value *TraceGroupsItem
	isSet bool
}

func (v NullableTraceGroupsItem) Get() *TraceGroupsItem {
	return v.value
}

func (v *NullableTraceGroupsItem) Set(val *TraceGroupsItem) {
	v.value = val
	v.isSet = true
}

func (v NullableTraceGroupsItem) IsSet() bool {
	return v.isSet
}

func (v *NullableTraceGroupsItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTraceGroupsItem(val *TraceGroupsItem) *NullableTraceGroupsItem {
	return &NullableTraceGroupsItem{value: val, isSet: true}
}

func (v NullableTraceGroupsItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTraceGroupsItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
