/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// ThresholdRuleAllOf struct for ThresholdRuleAllOf
type ThresholdRuleAllOf struct {
	MetricName        string        `json:"metricName,omitempty"`
	MetricPattern     MetricPattern `json:"metricPattern,omitempty"`
	Rollup            int64         `json:"rollup,omitempty"`
	Window            int64         `json:"window,omitempty"`
	Aggregation       string        `json:"aggregation,omitempty"`
	ConditionOperator string        `json:"conditionOperator,omitempty"`
	ConditionValue    float64       `json:"conditionValue,omitempty"`
}
