/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// TagTreeLevel struct for TagTreeLevel
type TagTreeLevel struct {
	Label       string        `json:"label"`
	Description string        `json:"description,omitempty"`
	Icon        string        `json:"icon,omitempty"`
	Searchable  bool          `json:"searchable"`
	Children    []TagTreeNode `json:"children"`
	Type        string        `json:"type,omitempty"`
}
