/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// MetricInstance struct for MetricInstance
type MetricInstance struct {
	Formatter   string `json:"formatter"`
	Label       string `json:"label"`
	Description string `json:"description"`
	MetricId    string `json:"metricId"`
	PluginId    string `json:"pluginId"`
	Custom      bool   `json:"custom,omitempty"`
}
