/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// HttpEndpointRule struct for HttpEndpointRule
type HttpEndpointRule struct {
	Enabled      bool                          `json:"enabled,omitempty"`
	PathSegments []HttpPathSegmentMatchingRule `json:"pathSegments"`
	TestCases    []string                      `json:"testCases,omitempty"`
}
