/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// Tag struct for Tag
type Tag struct {
	Name                  string `json:"name"`
	Label                 string `json:"label,omitempty"`
	Type                  string `json:"type"`
	Description           string `json:"description,omitempty"`
	CanApplyToSource      bool   `json:"canApplyToSource,omitempty"`
	CanApplyToDestination bool   `json:"canApplyToDestination,omitempty"`
}
