/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// ServiceScope struct for ServiceScope
type ServiceScope struct {
	Name     string           `json:"name"`
	ScopedTo *ServiceScopedTo `json:"scopedTo,omitempty"`
}

// NewServiceScope instantiates a new ServiceScope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceScope(name string) *ServiceScope {
	this := ServiceScope{}
	this.Name = name
	return &this
}

// NewServiceScopeWithDefaults instantiates a new ServiceScope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceScopeWithDefaults() *ServiceScope {
	this := ServiceScope{}
	return &this
}

// GetName returns the Name field value
func (o *ServiceScope) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServiceScope) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServiceScope) SetName(v string) {
	o.Name = v
}

// GetScopedTo returns the ScopedTo field value if set, zero value otherwise.
func (o *ServiceScope) GetScopedTo() ServiceScopedTo {
	if o == nil || o.ScopedTo == nil {
		var ret ServiceScopedTo
		return ret
	}
	return *o.ScopedTo
}

// GetScopedToOk returns a tuple with the ScopedTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceScope) GetScopedToOk() (*ServiceScopedTo, bool) {
	if o == nil || o.ScopedTo == nil {
		return nil, false
	}
	return o.ScopedTo, true
}

// HasScopedTo returns a boolean if a field has been set.
func (o *ServiceScope) HasScopedTo() bool {
	if o != nil && o.ScopedTo != nil {
		return true
	}

	return false
}

// SetScopedTo gets a reference to the given ServiceScopedTo and assigns it to the ScopedTo field.
func (o *ServiceScope) SetScopedTo(v ServiceScopedTo) {
	o.ScopedTo = &v
}

func (o ServiceScope) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.ScopedTo != nil {
		toSerialize["scopedTo"] = o.ScopedTo
	}
	return json.Marshal(toSerialize)
}

type NullableServiceScope struct {
	value *ServiceScope
	isSet bool
}

func (v NullableServiceScope) Get() *ServiceScope {
	return v.value
}

func (v *NullableServiceScope) Set(val *ServiceScope) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceScope) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceScope(val *ServiceScope) *NullableServiceScope {
	return &NullableServiceScope{value: val, isSet: true}
}

func (v NullableServiceScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
