/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// WebsiteBeaconGroupsItem struct for WebsiteBeaconGroupsItem
type WebsiteBeaconGroupsItem struct {
	Name              string                 `json:"name"`
	EarliestTimestamp *int64                 `json:"earliestTimestamp,omitempty"`
	Cursor            IngestionOffsetCursor  `json:"cursor"`
	Metrics           map[string][][]float32 `json:"metrics"`
}

// NewWebsiteBeaconGroupsItem instantiates a new WebsiteBeaconGroupsItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebsiteBeaconGroupsItem(name string, cursor IngestionOffsetCursor, metrics map[string][][]float32) *WebsiteBeaconGroupsItem {
	this := WebsiteBeaconGroupsItem{}
	this.Name = name
	this.Cursor = cursor
	this.Metrics = metrics
	return &this
}

// NewWebsiteBeaconGroupsItemWithDefaults instantiates a new WebsiteBeaconGroupsItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebsiteBeaconGroupsItemWithDefaults() *WebsiteBeaconGroupsItem {
	this := WebsiteBeaconGroupsItem{}
	return &this
}

// GetName returns the Name field value
func (o *WebsiteBeaconGroupsItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WebsiteBeaconGroupsItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WebsiteBeaconGroupsItem) SetName(v string) {
	o.Name = v
}

// GetEarliestTimestamp returns the EarliestTimestamp field value if set, zero value otherwise.
func (o *WebsiteBeaconGroupsItem) GetEarliestTimestamp() int64 {
	if o == nil || o.EarliestTimestamp == nil {
		var ret int64
		return ret
	}
	return *o.EarliestTimestamp
}

// GetEarliestTimestampOk returns a tuple with the EarliestTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebsiteBeaconGroupsItem) GetEarliestTimestampOk() (*int64, bool) {
	if o == nil || o.EarliestTimestamp == nil {
		return nil, false
	}
	return o.EarliestTimestamp, true
}

// HasEarliestTimestamp returns a boolean if a field has been set.
func (o *WebsiteBeaconGroupsItem) HasEarliestTimestamp() bool {
	if o != nil && o.EarliestTimestamp != nil {
		return true
	}

	return false
}

// SetEarliestTimestamp gets a reference to the given int64 and assigns it to the EarliestTimestamp field.
func (o *WebsiteBeaconGroupsItem) SetEarliestTimestamp(v int64) {
	o.EarliestTimestamp = &v
}

// GetCursor returns the Cursor field value
func (o *WebsiteBeaconGroupsItem) GetCursor() IngestionOffsetCursor {
	if o == nil {
		var ret IngestionOffsetCursor
		return ret
	}

	return o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value
// and a boolean to check if the value has been set.
func (o *WebsiteBeaconGroupsItem) GetCursorOk() (*IngestionOffsetCursor, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cursor, true
}

// SetCursor sets field value
func (o *WebsiteBeaconGroupsItem) SetCursor(v IngestionOffsetCursor) {
	o.Cursor = v
}

// GetMetrics returns the Metrics field value
func (o *WebsiteBeaconGroupsItem) GetMetrics() map[string][][]float32 {
	if o == nil {
		var ret map[string][][]float32
		return ret
	}

	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value
// and a boolean to check if the value has been set.
func (o *WebsiteBeaconGroupsItem) GetMetricsOk() (*map[string][][]float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metrics, true
}

// SetMetrics sets field value
func (o *WebsiteBeaconGroupsItem) SetMetrics(v map[string][][]float32) {
	o.Metrics = v
}

func (o WebsiteBeaconGroupsItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.EarliestTimestamp != nil {
		toSerialize["earliestTimestamp"] = o.EarliestTimestamp
	}
	if true {
		toSerialize["cursor"] = o.Cursor
	}
	if true {
		toSerialize["metrics"] = o.Metrics
	}
	return json.Marshal(toSerialize)
}

type NullableWebsiteBeaconGroupsItem struct {
	value *WebsiteBeaconGroupsItem
	isSet bool
}

func (v NullableWebsiteBeaconGroupsItem) Get() *WebsiteBeaconGroupsItem {
	return v.value
}

func (v *NullableWebsiteBeaconGroupsItem) Set(val *WebsiteBeaconGroupsItem) {
	v.value = val
	v.isSet = true
}

func (v NullableWebsiteBeaconGroupsItem) IsSet() bool {
	return v.isSet
}

func (v *NullableWebsiteBeaconGroupsItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebsiteBeaconGroupsItem(val *WebsiteBeaconGroupsItem) *NullableWebsiteBeaconGroupsItem {
	return &NullableWebsiteBeaconGroupsItem{value: val, isSet: true}
}

func (v NullableWebsiteBeaconGroupsItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebsiteBeaconGroupsItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
