/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// EndpointItem struct for EndpointItem
type EndpointItem struct {
	Endpoint Endpoint               `json:"endpoint"`
	Metrics  map[string][][]float32 `json:"metrics"`
}
