/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// MatchAllHttpPathSegmentMatchingRule struct for MatchAllHttpPathSegmentMatchingRule
type MatchAllHttpPathSegmentMatchingRule struct {
	HttpPathSegmentMatchingRule
}

// NewMatchAllHttpPathSegmentMatchingRule instantiates a new MatchAllHttpPathSegmentMatchingRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMatchAllHttpPathSegmentMatchingRule() *MatchAllHttpPathSegmentMatchingRule {
	this := MatchAllHttpPathSegmentMatchingRule{}
	return &this
}

// NewMatchAllHttpPathSegmentMatchingRuleWithDefaults instantiates a new MatchAllHttpPathSegmentMatchingRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMatchAllHttpPathSegmentMatchingRuleWithDefaults() *MatchAllHttpPathSegmentMatchingRule {
	this := MatchAllHttpPathSegmentMatchingRule{}
	return &this
}

func (o MatchAllHttpPathSegmentMatchingRule) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedHttpPathSegmentMatchingRule, errHttpPathSegmentMatchingRule := json.Marshal(o.HttpPathSegmentMatchingRule)
	if errHttpPathSegmentMatchingRule != nil {
		return []byte{}, errHttpPathSegmentMatchingRule
	}
	errHttpPathSegmentMatchingRule = json.Unmarshal([]byte(serializedHttpPathSegmentMatchingRule), &toSerialize)
	if errHttpPathSegmentMatchingRule != nil {
		return []byte{}, errHttpPathSegmentMatchingRule
	}
	return json.Marshal(toSerialize)
}

type NullableMatchAllHttpPathSegmentMatchingRule struct {
	value *MatchAllHttpPathSegmentMatchingRule
	isSet bool
}

func (v NullableMatchAllHttpPathSegmentMatchingRule) Get() *MatchAllHttpPathSegmentMatchingRule {
	return v.value
}

func (v *NullableMatchAllHttpPathSegmentMatchingRule) Set(val *MatchAllHttpPathSegmentMatchingRule) {
	v.value = val
	v.isSet = true
}

func (v NullableMatchAllHttpPathSegmentMatchingRule) IsSet() bool {
	return v.isSet
}

func (v *NullableMatchAllHttpPathSegmentMatchingRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMatchAllHttpPathSegmentMatchingRule(val *MatchAllHttpPathSegmentMatchingRule) *NullableMatchAllHttpPathSegmentMatchingRule {
	return &NullableMatchAllHttpPathSegmentMatchingRule{value: val, isSet: true}
}

func (v NullableMatchAllHttpPathSegmentMatchingRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMatchAllHttpPathSegmentMatchingRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
