/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// Trace struct for Trace
type Trace struct {
	Id        string   `json:"id"`
	Label     string   `json:"label"`
	StartTime int64    `json:"startTime,omitempty"`
	Duration  int64    `json:"duration,omitempty"`
	Erroneous bool     `json:"erroneous,omitempty"`
	Service   Service  `json:"service,omitempty"`
	Endpoint  Endpoint `json:"endpoint,omitempty"`
}
