/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// SpanRelation struct for SpanRelation
type SpanRelation struct {
	Applications    []Application   `json:"applications"`
	Service         Service         `json:"service,omitempty"`
	Endpoint        Endpoint        `json:"endpoint,omitempty"`
	PhysicalContext PhysicalContext `json:"physicalContext,omitempty"`
}
