/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// TimeFrame struct for TimeFrame
type TimeFrame struct {
	WindowSize int64 `json:"windowSize,omitempty"`
	To         int64 `json:"to,omitempty"`
}
