/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// Endpoint struct for Endpoint
type Endpoint struct {
	Id            string   `json:"id"`
	Label         string   `json:"label"`
	Type          string   `json:"type"`
	ServiceId     string   `json:"serviceId"`
	Technologies  []string `json:"technologies"`
	IsSynthetic   bool     `json:"isSynthetic,omitempty"`
	SyntheticType string   `json:"syntheticType,omitempty"`
	Synthetic     bool     `json:"synthetic,omitempty"`
	EntityType    string   `json:"entityType,omitempty"`
}
