/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// SliReport struct for SliReport
type SliReport struct {
	Sli                   float64          `json:"sli,omitempty"`
	Slo                   float64          `json:"slo,omitempty"`
	TotalErrorBudget      int32            `json:"totalErrorBudget,omitempty"`
	ErrorBudgetRemaining  int32            `json:"errorBudgetRemaining,omitempty"`
	FromTimestamp         int64            `json:"fromTimestamp,omitempty"`
	ToTimestamp           int64            `json:"toTimestamp,omitempty"`
	ViolationDistribution map[string]int32 `json:"violationDistribution,omitempty"`
}
