/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// GoogleChatIntegrationAllOf struct for GoogleChatIntegrationAllOf
type GoogleChatIntegrationAllOf struct {
	WebhookUrl *string `json:"webhookUrl,omitempty"`
}

// NewGoogleChatIntegrationAllOf instantiates a new GoogleChatIntegrationAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleChatIntegrationAllOf() *GoogleChatIntegrationAllOf {
	this := GoogleChatIntegrationAllOf{}
	return &this
}

// NewGoogleChatIntegrationAllOfWithDefaults instantiates a new GoogleChatIntegrationAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleChatIntegrationAllOfWithDefaults() *GoogleChatIntegrationAllOf {
	this := GoogleChatIntegrationAllOf{}
	return &this
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise.
func (o *GoogleChatIntegrationAllOf) GetWebhookUrl() string {
	if o == nil || o.WebhookUrl == nil {
		var ret string
		return ret
	}
	return *o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleChatIntegrationAllOf) GetWebhookUrlOk() (*string, bool) {
	if o == nil || o.WebhookUrl == nil {
		return nil, false
	}
	return o.WebhookUrl, true
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *GoogleChatIntegrationAllOf) HasWebhookUrl() bool {
	if o != nil && o.WebhookUrl != nil {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given string and assigns it to the WebhookUrl field.
func (o *GoogleChatIntegrationAllOf) SetWebhookUrl(v string) {
	o.WebhookUrl = &v
}

func (o GoogleChatIntegrationAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.WebhookUrl != nil {
		toSerialize["webhookUrl"] = o.WebhookUrl
	}
	return json.Marshal(toSerialize)
}

type NullableGoogleChatIntegrationAllOf struct {
	value *GoogleChatIntegrationAllOf
	isSet bool
}

func (v NullableGoogleChatIntegrationAllOf) Get() *GoogleChatIntegrationAllOf {
	return v.value
}

func (v *NullableGoogleChatIntegrationAllOf) Set(val *GoogleChatIntegrationAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleChatIntegrationAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleChatIntegrationAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleChatIntegrationAllOf(val *GoogleChatIntegrationAllOf) *NullableGoogleChatIntegrationAllOf {
	return &NullableGoogleChatIntegrationAllOf{value: val, isSet: true}
}

func (v NullableGoogleChatIntegrationAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleChatIntegrationAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
