/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// RbacGroup struct for RbacGroup
type RbacGroup struct {
	Id            string        `json:"id,omitempty"`
	Name          string        `json:"name"`
	Members       []Member      `json:"members"`
	PermissionSet PermissionSet `json:"permissionSet,omitempty"`
}
