/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// StaticNumberField struct for StaticNumberField
type StaticNumberField struct {
	CustomPayloadField
	Value float32 `json:"value"`
}

// NewStaticNumberField instantiates a new StaticNumberField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStaticNumberField(value float32) *StaticNumberField {
	this := StaticNumberField{}
	this.Value = value
	return &this
}

// NewStaticNumberFieldWithDefaults instantiates a new StaticNumberField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStaticNumberFieldWithDefaults() *StaticNumberField {
	this := StaticNumberField{}
	return &this
}

// GetValue returns the Value field value
func (o *StaticNumberField) GetValue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *StaticNumberField) GetValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *StaticNumberField) SetValue(v float32) {
	o.Value = v
}

func (o StaticNumberField) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedCustomPayloadField, errCustomPayloadField := json.Marshal(o.CustomPayloadField)
	if errCustomPayloadField != nil {
		return []byte{}, errCustomPayloadField
	}
	errCustomPayloadField = json.Unmarshal([]byte(serializedCustomPayloadField), &toSerialize)
	if errCustomPayloadField != nil {
		return []byte{}, errCustomPayloadField
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableStaticNumberField struct {
	value *StaticNumberField
	isSet bool
}

func (v NullableStaticNumberField) Get() *StaticNumberField {
	return v.value
}

func (v *NullableStaticNumberField) Set(val *StaticNumberField) {
	v.value = val
	v.isSet = true
}

func (v NullableStaticNumberField) IsSet() bool {
	return v.isSet
}

func (v *NullableStaticNumberField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStaticNumberField(val *StaticNumberField) *NullableStaticNumberField {
	return &NullableStaticNumberField{value: val, isSet: true}
}

func (v NullableStaticNumberField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStaticNumberField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
