/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// KubernetesPhysicalContext struct for KubernetesPhysicalContext
type KubernetesPhysicalContext struct {
	Pod       SnapshotPreview `json:"pod,omitempty"`
	Namespace SnapshotPreview `json:"namespace,omitempty"`
	Node      SnapshotPreview `json:"node,omitempty"`
	Cluster   SnapshotPreview `json:"cluster,omitempty"`
}
