/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// GetWebsiteMetrics struct for GetWebsiteMetrics
type GetWebsiteMetrics struct {
	TimeFrame  *TimeFrame                              `json:"timeFrame,omitempty"`
	Metrics    []WebsiteMonitoringMetricsConfiguration `json:"metrics"`
	Type       string                                  `json:"type"`
	TagFilters *[]TagFilter                            `json:"tagFilters,omitempty"`
}

// NewGetWebsiteMetrics instantiates a new GetWebsiteMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWebsiteMetrics(metrics []WebsiteMonitoringMetricsConfiguration, type_ string) *GetWebsiteMetrics {
	this := GetWebsiteMetrics{}
	this.Metrics = metrics
	this.Type = type_
	return &this
}

// NewGetWebsiteMetricsWithDefaults instantiates a new GetWebsiteMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWebsiteMetricsWithDefaults() *GetWebsiteMetrics {
	this := GetWebsiteMetrics{}
	return &this
}

// GetTimeFrame returns the TimeFrame field value if set, zero value otherwise.
func (o *GetWebsiteMetrics) GetTimeFrame() TimeFrame {
	if o == nil || o.TimeFrame == nil {
		var ret TimeFrame
		return ret
	}
	return *o.TimeFrame
}

// GetTimeFrameOk returns a tuple with the TimeFrame field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebsiteMetrics) GetTimeFrameOk() (*TimeFrame, bool) {
	if o == nil || o.TimeFrame == nil {
		return nil, false
	}
	return o.TimeFrame, true
}

// HasTimeFrame returns a boolean if a field has been set.
func (o *GetWebsiteMetrics) HasTimeFrame() bool {
	if o != nil && o.TimeFrame != nil {
		return true
	}

	return false
}

// SetTimeFrame gets a reference to the given TimeFrame and assigns it to the TimeFrame field.
func (o *GetWebsiteMetrics) SetTimeFrame(v TimeFrame) {
	o.TimeFrame = &v
}

// GetMetrics returns the Metrics field value
func (o *GetWebsiteMetrics) GetMetrics() []WebsiteMonitoringMetricsConfiguration {
	if o == nil {
		var ret []WebsiteMonitoringMetricsConfiguration
		return ret
	}

	return o.Metrics
}

// GetMetricsOk returns a tuple with the Metrics field value
// and a boolean to check if the value has been set.
func (o *GetWebsiteMetrics) GetMetricsOk() (*[]WebsiteMonitoringMetricsConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metrics, true
}

// SetMetrics sets field value
func (o *GetWebsiteMetrics) SetMetrics(v []WebsiteMonitoringMetricsConfiguration) {
	o.Metrics = v
}

// GetType returns the Type field value
func (o *GetWebsiteMetrics) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetWebsiteMetrics) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetWebsiteMetrics) SetType(v string) {
	o.Type = v
}

// GetTagFilters returns the TagFilters field value if set, zero value otherwise.
func (o *GetWebsiteMetrics) GetTagFilters() []TagFilter {
	if o == nil || o.TagFilters == nil {
		var ret []TagFilter
		return ret
	}
	return *o.TagFilters
}

// GetTagFiltersOk returns a tuple with the TagFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebsiteMetrics) GetTagFiltersOk() (*[]TagFilter, bool) {
	if o == nil || o.TagFilters == nil {
		return nil, false
	}
	return o.TagFilters, true
}

// HasTagFilters returns a boolean if a field has been set.
func (o *GetWebsiteMetrics) HasTagFilters() bool {
	if o != nil && o.TagFilters != nil {
		return true
	}

	return false
}

// SetTagFilters gets a reference to the given []TagFilter and assigns it to the TagFilters field.
func (o *GetWebsiteMetrics) SetTagFilters(v []TagFilter) {
	o.TagFilters = &v
}

func (o GetWebsiteMetrics) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TimeFrame != nil {
		toSerialize["timeFrame"] = o.TimeFrame
	}
	if true {
		toSerialize["metrics"] = o.Metrics
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if o.TagFilters != nil {
		toSerialize["tagFilters"] = o.TagFilters
	}
	return json.Marshal(toSerialize)
}

type NullableGetWebsiteMetrics struct {
	value *GetWebsiteMetrics
	isSet bool
}

func (v NullableGetWebsiteMetrics) Get() *GetWebsiteMetrics {
	return v.value
}

func (v *NullableGetWebsiteMetrics) Set(val *GetWebsiteMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWebsiteMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWebsiteMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWebsiteMetrics(val *GetWebsiteMetrics) *NullableGetWebsiteMetrics {
	return &NullableGetWebsiteMetrics{value: val, isSet: true}
}

func (v NullableGetWebsiteMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWebsiteMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
