/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// GetTraces struct for GetTraces
type GetTraces struct {
	Pagination *CursorPagination `json:"pagination,omitempty"`
	TimeFrame  *TimeFrame        `json:"timeFrame,omitempty"`
	TagFilters *[]TagFilter      `json:"tagFilters,omitempty"`
}

// NewGetTraces instantiates a new GetTraces object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTraces() *GetTraces {
	this := GetTraces{}
	return &this
}

// NewGetTracesWithDefaults instantiates a new GetTraces object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTracesWithDefaults() *GetTraces {
	this := GetTraces{}
	return &this
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *GetTraces) GetPagination() CursorPagination {
	if o == nil || o.Pagination == nil {
		var ret CursorPagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTraces) GetPaginationOk() (*CursorPagination, bool) {
	if o == nil || o.Pagination == nil {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *GetTraces) HasPagination() bool {
	if o != nil && o.Pagination != nil {
		return true
	}

	return false
}

// SetPagination gets a reference to the given CursorPagination and assigns it to the Pagination field.
func (o *GetTraces) SetPagination(v CursorPagination) {
	o.Pagination = &v
}

// GetTimeFrame returns the TimeFrame field value if set, zero value otherwise.
func (o *GetTraces) GetTimeFrame() TimeFrame {
	if o == nil || o.TimeFrame == nil {
		var ret TimeFrame
		return ret
	}
	return *o.TimeFrame
}

// GetTimeFrameOk returns a tuple with the TimeFrame field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTraces) GetTimeFrameOk() (*TimeFrame, bool) {
	if o == nil || o.TimeFrame == nil {
		return nil, false
	}
	return o.TimeFrame, true
}

// HasTimeFrame returns a boolean if a field has been set.
func (o *GetTraces) HasTimeFrame() bool {
	if o != nil && o.TimeFrame != nil {
		return true
	}

	return false
}

// SetTimeFrame gets a reference to the given TimeFrame and assigns it to the TimeFrame field.
func (o *GetTraces) SetTimeFrame(v TimeFrame) {
	o.TimeFrame = &v
}

// GetTagFilters returns the TagFilters field value if set, zero value otherwise.
func (o *GetTraces) GetTagFilters() []TagFilter {
	if o == nil || o.TagFilters == nil {
		var ret []TagFilter
		return ret
	}
	return *o.TagFilters
}

// GetTagFiltersOk returns a tuple with the TagFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTraces) GetTagFiltersOk() (*[]TagFilter, bool) {
	if o == nil || o.TagFilters == nil {
		return nil, false
	}
	return o.TagFilters, true
}

// HasTagFilters returns a boolean if a field has been set.
func (o *GetTraces) HasTagFilters() bool {
	if o != nil && o.TagFilters != nil {
		return true
	}

	return false
}

// SetTagFilters gets a reference to the given []TagFilter and assigns it to the TagFilters field.
func (o *GetTraces) SetTagFilters(v []TagFilter) {
	o.TagFilters = &v
}

func (o GetTraces) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pagination != nil {
		toSerialize["pagination"] = o.Pagination
	}
	if o.TimeFrame != nil {
		toSerialize["timeFrame"] = o.TimeFrame
	}
	if o.TagFilters != nil {
		toSerialize["tagFilters"] = o.TagFilters
	}
	return json.Marshal(toSerialize)
}

type NullableGetTraces struct {
	value *GetTraces
	isSet bool
}

func (v NullableGetTraces) Get() *GetTraces {
	return v.value
}

func (v *NullableGetTraces) Set(val *GetTraces) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTraces) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTraces) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTraces(val *GetTraces) *NullableGetTraces {
	return &NullableGetTraces{value: val, isSet: true}
}

func (v NullableGetTraces) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTraces) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
