/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// StaticThresholdAllOf struct for StaticThresholdAllOf
type StaticThresholdAllOf struct {
	Value *float64 `json:"value,omitempty"`
}

// NewStaticThresholdAllOf instantiates a new StaticThresholdAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStaticThresholdAllOf() *StaticThresholdAllOf {
	this := StaticThresholdAllOf{}
	return &this
}

// NewStaticThresholdAllOfWithDefaults instantiates a new StaticThresholdAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStaticThresholdAllOfWithDefaults() *StaticThresholdAllOf {
	this := StaticThresholdAllOf{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *StaticThresholdAllOf) GetValue() float64 {
	if o == nil || o.Value == nil {
		var ret float64
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StaticThresholdAllOf) GetValueOk() (*float64, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *StaticThresholdAllOf) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given float64 and assigns it to the Value field.
func (o *StaticThresholdAllOf) SetValue(v float64) {
	o.Value = &v
}

func (o StaticThresholdAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableStaticThresholdAllOf struct {
	value *StaticThresholdAllOf
	isSet bool
}

func (v NullableStaticThresholdAllOf) Get() *StaticThresholdAllOf {
	return v.value
}

func (v *NullableStaticThresholdAllOf) Set(val *StaticThresholdAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableStaticThresholdAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableStaticThresholdAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStaticThresholdAllOf(val *StaticThresholdAllOf) *NullableStaticThresholdAllOf {
	return &NullableStaticThresholdAllOf{value: val, isSet: true}
}

func (v NullableStaticThresholdAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStaticThresholdAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
