/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// StaticStringField struct for StaticStringField
type StaticStringField struct {
	CustomPayloadField
	Value string `json:"value"`
}

// NewStaticStringField instantiates a new StaticStringField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStaticStringField(value string) *StaticStringField {
	this := StaticStringField{}
	this.Value = value
	return &this
}

// NewStaticStringFieldWithDefaults instantiates a new StaticStringField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStaticStringFieldWithDefaults() *StaticStringField {
	this := StaticStringField{}
	return &this
}

// GetValue returns the Value field value
func (o *StaticStringField) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *StaticStringField) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *StaticStringField) SetValue(v string) {
	o.Value = v
}

func (o StaticStringField) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedCustomPayloadField, errCustomPayloadField := json.Marshal(o.CustomPayloadField)
	if errCustomPayloadField != nil {
		return []byte{}, errCustomPayloadField
	}
	errCustomPayloadField = json.Unmarshal([]byte(serializedCustomPayloadField), &toSerialize)
	if errCustomPayloadField != nil {
		return []byte{}, errCustomPayloadField
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableStaticStringField struct {
	value *StaticStringField
	isSet bool
}

func (v NullableStaticStringField) Get() *StaticStringField {
	return v.value
}

func (v *NullableStaticStringField) Set(val *StaticStringField) {
	v.value = val
	v.isSet = true
}

func (v NullableStaticStringField) IsSet() bool {
	return v.isSet
}

func (v *NullableStaticStringField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStaticStringField(val *StaticStringField) *NullableStaticStringField {
	return &NullableStaticStringField{value: val, isSet: true}
}

func (v NullableStaticStringField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStaticStringField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
