/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// EntityVerificationRuleAllOf struct for EntityVerificationRuleAllOf
type EntityVerificationRuleAllOf struct {
	MatchingEntityType  string `json:"matchingEntityType,omitempty"`
	MatchingOperator    string `json:"matchingOperator,omitempty"`
	MatchingEntityLabel string `json:"matchingEntityLabel,omitempty"`
	OfflineDuration     int64  `json:"offlineDuration,omitempty"`
}
