/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// Group struct for Group
type Group struct {
	GroupbyTag               string  `json:"groupbyTag"`
	GroupbyTagSecondLevelKey *string `json:"groupbyTagSecondLevelKey,omitempty"`
	GroupbyTagEntity         string  `json:"groupbyTagEntity"`
}

// NewGroup instantiates a new Group object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroup(groupbyTag string, groupbyTagEntity string) *Group {
	this := Group{}
	this.GroupbyTag = groupbyTag
	this.GroupbyTagEntity = groupbyTagEntity
	return &this
}

// NewGroupWithDefaults instantiates a new Group object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupWithDefaults() *Group {
	this := Group{}
	return &this
}

// GetGroupbyTag returns the GroupbyTag field value
func (o *Group) GetGroupbyTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupbyTag
}

// GetGroupbyTagOk returns a tuple with the GroupbyTag field value
// and a boolean to check if the value has been set.
func (o *Group) GetGroupbyTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupbyTag, true
}

// SetGroupbyTag sets field value
func (o *Group) SetGroupbyTag(v string) {
	o.GroupbyTag = v
}

// GetGroupbyTagSecondLevelKey returns the GroupbyTagSecondLevelKey field value if set, zero value otherwise.
func (o *Group) GetGroupbyTagSecondLevelKey() string {
	if o == nil || o.GroupbyTagSecondLevelKey == nil {
		var ret string
		return ret
	}
	return *o.GroupbyTagSecondLevelKey
}

// GetGroupbyTagSecondLevelKeyOk returns a tuple with the GroupbyTagSecondLevelKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Group) GetGroupbyTagSecondLevelKeyOk() (*string, bool) {
	if o == nil || o.GroupbyTagSecondLevelKey == nil {
		return nil, false
	}
	return o.GroupbyTagSecondLevelKey, true
}

// HasGroupbyTagSecondLevelKey returns a boolean if a field has been set.
func (o *Group) HasGroupbyTagSecondLevelKey() bool {
	if o != nil && o.GroupbyTagSecondLevelKey != nil {
		return true
	}

	return false
}

// SetGroupbyTagSecondLevelKey gets a reference to the given string and assigns it to the GroupbyTagSecondLevelKey field.
func (o *Group) SetGroupbyTagSecondLevelKey(v string) {
	o.GroupbyTagSecondLevelKey = &v
}

// GetGroupbyTagEntity returns the GroupbyTagEntity field value
func (o *Group) GetGroupbyTagEntity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GroupbyTagEntity
}

// GetGroupbyTagEntityOk returns a tuple with the GroupbyTagEntity field value
// and a boolean to check if the value has been set.
func (o *Group) GetGroupbyTagEntityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GroupbyTagEntity, true
}

// SetGroupbyTagEntity sets field value
func (o *Group) SetGroupbyTagEntity(v string) {
	o.GroupbyTagEntity = v
}

func (o Group) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["groupbyTag"] = o.GroupbyTag
	}
	if o.GroupbyTagSecondLevelKey != nil {
		toSerialize["groupbyTagSecondLevelKey"] = o.GroupbyTagSecondLevelKey
	}
	if true {
		toSerialize["groupbyTagEntity"] = o.GroupbyTagEntity
	}
	return json.Marshal(toSerialize)
}

type NullableGroup struct {
	value *Group
	isSet bool
}

func (v NullableGroup) Get() *Group {
	return v.value
}

func (v *NullableGroup) Set(val *Group) {
	v.value = val
	v.isSet = true
}

func (v NullableGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroup(val *Group) *NullableGroup {
	return &NullableGroup{value: val, isSet: true}
}

func (v NullableGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
