/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// MaintenanceConfigWithLastUpdated struct for MaintenanceConfigWithLastUpdated
type MaintenanceConfigWithLastUpdated struct {
	Id          string              `json:"id"`
	Name        string              `json:"name"`
	Query       string              `json:"query"`
	Windows     []MaintenanceWindow `json:"windows,omitempty"`
	LastUpdated int64               `json:"lastUpdated,omitempty"`
}
