/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// Office365Integration struct for Office365Integration
type Office365Integration struct {
	AbstractIntegration
	WebhookUrl string `json:"webhookUrl"`
}

// NewOffice365Integration instantiates a new Office365Integration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOffice365Integration(webhookUrl string) *Office365Integration {
	this := Office365Integration{}
	this.WebhookUrl = webhookUrl
	return &this
}

// NewOffice365IntegrationWithDefaults instantiates a new Office365Integration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOffice365IntegrationWithDefaults() *Office365Integration {
	this := Office365Integration{}
	return &this
}

// GetWebhookUrl returns the WebhookUrl field value
func (o *Office365Integration) GetWebhookUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value
// and a boolean to check if the value has been set.
func (o *Office365Integration) GetWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WebhookUrl, true
}

// SetWebhookUrl sets field value
func (o *Office365Integration) SetWebhookUrl(v string) {
	o.WebhookUrl = v
}

func (o Office365Integration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedAbstractIntegration, errAbstractIntegration := json.Marshal(o.AbstractIntegration)
	if errAbstractIntegration != nil {
		return []byte{}, errAbstractIntegration
	}
	errAbstractIntegration = json.Unmarshal([]byte(serializedAbstractIntegration), &toSerialize)
	if errAbstractIntegration != nil {
		return []byte{}, errAbstractIntegration
	}
	if true {
		toSerialize["webhookUrl"] = o.WebhookUrl
	}
	return json.Marshal(toSerialize)
}

type NullableOffice365Integration struct {
	value *Office365Integration
	isSet bool
}

func (v NullableOffice365Integration) Get() *Office365Integration {
	return v.value
}

func (v *NullableOffice365Integration) Set(val *Office365Integration) {
	v.value = val
	v.isSet = true
}

func (v NullableOffice365Integration) IsSet() bool {
	return v.isSet
}

func (v *NullableOffice365Integration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOffice365Integration(val *Office365Integration) *NullableOffice365Integration {
	return &NullableOffice365Integration{value: val, isSet: true}
}

func (v NullableOffice365Integration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOffice365Integration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
