/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// AvailabilitySliEntity struct for AvailabilitySliEntity
type AvailabilitySliEntity struct {
	SliType          string      `json:"sliType"`
	ApplicationId    string      `json:"applicationId,omitempty"`
	ServiceId        string      `json:"serviceId,omitempty"`
	EndpointId       string      `json:"endpointId,omitempty"`
	BoundaryScope    string      `json:"boundaryScope"`
	GoodEventFilters []TagFilter `json:"goodEventFilters"`
	BadEventFilters  []TagFilter `json:"badEventFilters"`
}
