/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// FixedHttpPathSegmentMatchingRuleAllOf struct for FixedHttpPathSegmentMatchingRuleAllOf
type FixedHttpPathSegmentMatchingRuleAllOf struct {
	Name string `json:"name,omitempty"`
}
