/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// CustomPayloadWithLastUpdated struct for CustomPayloadWithLastUpdated
type CustomPayloadWithLastUpdated struct {
	Fields      []CustomPayloadField `json:"fields"`
	LastUpdated int64                `json:"lastUpdated,omitempty"`
}
