/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// IngestionOffsetCursor struct for IngestionOffsetCursor
type IngestionOffsetCursor struct {
	IngestionTime *int64 `json:"ingestionTime,omitempty"`
	Offset        *int32 `json:"offset,omitempty"`
}

// NewIngestionOffsetCursor instantiates a new IngestionOffsetCursor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngestionOffsetCursor() *IngestionOffsetCursor {
	this := IngestionOffsetCursor{}
	return &this
}

// NewIngestionOffsetCursorWithDefaults instantiates a new IngestionOffsetCursor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngestionOffsetCursorWithDefaults() *IngestionOffsetCursor {
	this := IngestionOffsetCursor{}
	return &this
}

// GetIngestionTime returns the IngestionTime field value if set, zero value otherwise.
func (o *IngestionOffsetCursor) GetIngestionTime() int64 {
	if o == nil || o.IngestionTime == nil {
		var ret int64
		return ret
	}
	return *o.IngestionTime
}

// GetIngestionTimeOk returns a tuple with the IngestionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngestionOffsetCursor) GetIngestionTimeOk() (*int64, bool) {
	if o == nil || o.IngestionTime == nil {
		return nil, false
	}
	return o.IngestionTime, true
}

// HasIngestionTime returns a boolean if a field has been set.
func (o *IngestionOffsetCursor) HasIngestionTime() bool {
	if o != nil && o.IngestionTime != nil {
		return true
	}

	return false
}

// SetIngestionTime gets a reference to the given int64 and assigns it to the IngestionTime field.
func (o *IngestionOffsetCursor) SetIngestionTime(v int64) {
	o.IngestionTime = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *IngestionOffsetCursor) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngestionOffsetCursor) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *IngestionOffsetCursor) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *IngestionOffsetCursor) SetOffset(v int32) {
	o.Offset = &v
}

func (o IngestionOffsetCursor) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IngestionTime != nil {
		toSerialize["ingestionTime"] = o.IngestionTime
	}
	if o.Offset != nil {
		toSerialize["offset"] = o.Offset
	}
	return json.Marshal(toSerialize)
}

type NullableIngestionOffsetCursor struct {
	value *IngestionOffsetCursor
	isSet bool
}

func (v NullableIngestionOffsetCursor) Get() *IngestionOffsetCursor {
	return v.value
}

func (v *NullableIngestionOffsetCursor) Set(val *IngestionOffsetCursor) {
	v.value = val
	v.isSet = true
}

func (v NullableIngestionOffsetCursor) IsSet() bool {
	return v.isSet
}

func (v *NullableIngestionOffsetCursor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngestionOffsetCursor(val *IngestionOffsetCursor) *NullableIngestionOffsetCursor {
	return &NullableIngestionOffsetCursor{value: val, isSet: true}
}

func (v NullableIngestionOffsetCursor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngestionOffsetCursor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
