/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// WebsiteMonitoringMetricsConfiguration struct for WebsiteMonitoringMetricsConfiguration
type WebsiteMonitoringMetricsConfiguration struct {
	Metric      string `json:"metric"`
	Granularity *int32 `json:"granularity,omitempty"`
	Aggregation string `json:"aggregation"`
}

// NewWebsiteMonitoringMetricsConfiguration instantiates a new WebsiteMonitoringMetricsConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebsiteMonitoringMetricsConfiguration(metric string, aggregation string) *WebsiteMonitoringMetricsConfiguration {
	this := WebsiteMonitoringMetricsConfiguration{}
	this.Metric = metric
	this.Aggregation = aggregation
	return &this
}

// NewWebsiteMonitoringMetricsConfigurationWithDefaults instantiates a new WebsiteMonitoringMetricsConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebsiteMonitoringMetricsConfigurationWithDefaults() *WebsiteMonitoringMetricsConfiguration {
	this := WebsiteMonitoringMetricsConfiguration{}
	return &this
}

// GetMetric returns the Metric field value
func (o *WebsiteMonitoringMetricsConfiguration) GetMetric() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Metric
}

// GetMetricOk returns a tuple with the Metric field value
// and a boolean to check if the value has been set.
func (o *WebsiteMonitoringMetricsConfiguration) GetMetricOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metric, true
}

// SetMetric sets field value
func (o *WebsiteMonitoringMetricsConfiguration) SetMetric(v string) {
	o.Metric = v
}

// GetGranularity returns the Granularity field value if set, zero value otherwise.
func (o *WebsiteMonitoringMetricsConfiguration) GetGranularity() int32 {
	if o == nil || o.Granularity == nil {
		var ret int32
		return ret
	}
	return *o.Granularity
}

// GetGranularityOk returns a tuple with the Granularity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebsiteMonitoringMetricsConfiguration) GetGranularityOk() (*int32, bool) {
	if o == nil || o.Granularity == nil {
		return nil, false
	}
	return o.Granularity, true
}

// HasGranularity returns a boolean if a field has been set.
func (o *WebsiteMonitoringMetricsConfiguration) HasGranularity() bool {
	if o != nil && o.Granularity != nil {
		return true
	}

	return false
}

// SetGranularity gets a reference to the given int32 and assigns it to the Granularity field.
func (o *WebsiteMonitoringMetricsConfiguration) SetGranularity(v int32) {
	o.Granularity = &v
}

// GetAggregation returns the Aggregation field value
func (o *WebsiteMonitoringMetricsConfiguration) GetAggregation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Aggregation
}

// GetAggregationOk returns a tuple with the Aggregation field value
// and a boolean to check if the value has been set.
func (o *WebsiteMonitoringMetricsConfiguration) GetAggregationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Aggregation, true
}

// SetAggregation sets field value
func (o *WebsiteMonitoringMetricsConfiguration) SetAggregation(v string) {
	o.Aggregation = v
}

func (o WebsiteMonitoringMetricsConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["metric"] = o.Metric
	}
	if o.Granularity != nil {
		toSerialize["granularity"] = o.Granularity
	}
	if true {
		toSerialize["aggregation"] = o.Aggregation
	}
	return json.Marshal(toSerialize)
}

type NullableWebsiteMonitoringMetricsConfiguration struct {
	value *WebsiteMonitoringMetricsConfiguration
	isSet bool
}

func (v NullableWebsiteMonitoringMetricsConfiguration) Get() *WebsiteMonitoringMetricsConfiguration {
	return v.value
}

func (v *NullableWebsiteMonitoringMetricsConfiguration) Set(val *WebsiteMonitoringMetricsConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableWebsiteMonitoringMetricsConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableWebsiteMonitoringMetricsConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebsiteMonitoringMetricsConfiguration(val *WebsiteMonitoringMetricsConfiguration) *NullableWebsiteMonitoringMetricsConfiguration {
	return &NullableWebsiteMonitoringMetricsConfiguration{value: val, isSet: true}
}

func (v NullableWebsiteMonitoringMetricsConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebsiteMonitoringMetricsConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
