/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// FixedHttpPathSegmentMatchingRuleAllOf struct for FixedHttpPathSegmentMatchingRuleAllOf
type FixedHttpPathSegmentMatchingRuleAllOf struct {
	Name *string `json:"name,omitempty"`
}

// NewFixedHttpPathSegmentMatchingRuleAllOf instantiates a new FixedHttpPathSegmentMatchingRuleAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFixedHttpPathSegmentMatchingRuleAllOf() *FixedHttpPathSegmentMatchingRuleAllOf {
	this := FixedHttpPathSegmentMatchingRuleAllOf{}
	return &this
}

// NewFixedHttpPathSegmentMatchingRuleAllOfWithDefaults instantiates a new FixedHttpPathSegmentMatchingRuleAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFixedHttpPathSegmentMatchingRuleAllOfWithDefaults() *FixedHttpPathSegmentMatchingRuleAllOf {
	this := FixedHttpPathSegmentMatchingRuleAllOf{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FixedHttpPathSegmentMatchingRuleAllOf) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FixedHttpPathSegmentMatchingRuleAllOf) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FixedHttpPathSegmentMatchingRuleAllOf) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FixedHttpPathSegmentMatchingRuleAllOf) SetName(v string) {
	o.Name = &v
}

func (o FixedHttpPathSegmentMatchingRuleAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableFixedHttpPathSegmentMatchingRuleAllOf struct {
	value *FixedHttpPathSegmentMatchingRuleAllOf
	isSet bool
}

func (v NullableFixedHttpPathSegmentMatchingRuleAllOf) Get() *FixedHttpPathSegmentMatchingRuleAllOf {
	return v.value
}

func (v *NullableFixedHttpPathSegmentMatchingRuleAllOf) Set(val *FixedHttpPathSegmentMatchingRuleAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableFixedHttpPathSegmentMatchingRuleAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableFixedHttpPathSegmentMatchingRuleAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFixedHttpPathSegmentMatchingRuleAllOf(val *FixedHttpPathSegmentMatchingRuleAllOf) *NullableFixedHttpPathSegmentMatchingRuleAllOf {
	return &NullableFixedHttpPathSegmentMatchingRuleAllOf{value: val, isSet: true}
}

func (v NullableFixedHttpPathSegmentMatchingRuleAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFixedHttpPathSegmentMatchingRuleAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
