/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// AlertingConfiguration struct for AlertingConfiguration
type AlertingConfiguration struct {
	Id                          string                      `json:"id"`
	AlertName                   string                      `json:"alertName"`
	MuteUntil                   int64                       `json:"muteUntil,omitempty"`
	IntegrationIds              []string                    `json:"integrationIds"`
	EventFilteringConfiguration EventFilteringConfiguration `json:"eventFilteringConfiguration"`
}
