/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// StaticNumberFieldAllOf struct for StaticNumberFieldAllOf
type StaticNumberFieldAllOf struct {
	Value float32 `json:"value,omitempty"`
}
