/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package instana

import (
	"encoding/json"
)

// TagTreeTagAllOf struct for TagTreeTagAllOf
type TagTreeTagAllOf struct {
	Description *string `json:"description,omitempty"`
	TagName     *string `json:"tagName,omitempty"`
}

// NewTagTreeTagAllOf instantiates a new TagTreeTagAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagTreeTagAllOf() *TagTreeTagAllOf {
	this := TagTreeTagAllOf{}
	return &this
}

// NewTagTreeTagAllOfWithDefaults instantiates a new TagTreeTagAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagTreeTagAllOfWithDefaults() *TagTreeTagAllOf {
	this := TagTreeTagAllOf{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TagTreeTagAllOf) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagTreeTagAllOf) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TagTreeTagAllOf) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TagTreeTagAllOf) SetDescription(v string) {
	o.Description = &v
}

// GetTagName returns the TagName field value if set, zero value otherwise.
func (o *TagTreeTagAllOf) GetTagName() string {
	if o == nil || o.TagName == nil {
		var ret string
		return ret
	}
	return *o.TagName
}

// GetTagNameOk returns a tuple with the TagName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TagTreeTagAllOf) GetTagNameOk() (*string, bool) {
	if o == nil || o.TagName == nil {
		return nil, false
	}
	return o.TagName, true
}

// HasTagName returns a boolean if a field has been set.
func (o *TagTreeTagAllOf) HasTagName() bool {
	if o != nil && o.TagName != nil {
		return true
	}

	return false
}

// SetTagName gets a reference to the given string and assigns it to the TagName field.
func (o *TagTreeTagAllOf) SetTagName(v string) {
	o.TagName = &v
}

func (o TagTreeTagAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.TagName != nil {
		toSerialize["tagName"] = o.TagName
	}
	return json.Marshal(toSerialize)
}

type NullableTagTreeTagAllOf struct {
	value *TagTreeTagAllOf
	isSet bool
}

func (v NullableTagTreeTagAllOf) Get() *TagTreeTagAllOf {
	return v.value
}

func (v *NullableTagTreeTagAllOf) Set(val *TagTreeTagAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableTagTreeTagAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableTagTreeTagAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagTreeTagAllOf(val *TagTreeTagAllOf) *NullableTagTreeTagAllOf {
	return &NullableTagTreeTagAllOf{value: val, isSet: true}
}

func (v NullableTagTreeTagAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagTreeTagAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
