/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// WebsiteBeaconGroupsItem struct for WebsiteBeaconGroupsItem
type WebsiteBeaconGroupsItem struct {
	Name              string                 `json:"name"`
	EarliestTimestamp int64                  `json:"earliestTimestamp,omitempty"`
	Cursor            IngestionOffsetCursor  `json:"cursor"`
	Metrics           map[string][][]float32 `json:"metrics"`
}
