/*
 * Introduction to Instana public APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.192.86
 * Contact: support@instana.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package instana

// EventSpecificationInfo struct for EventSpecificationInfo
type EventSpecificationInfo struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
	EntityType  string `json:"entityType"`
	Type        string `json:"type"`
	Severity    int32  `json:"severity,omitempty"`
	Triggering  bool   `json:"triggering,omitempty"`
	Invalid     bool   `json:"invalid,omitempty"`
	Enabled     bool   `json:"enabled,omitempty"`
}
